### PR TITLE
doc: add fastquorum subway diagram

### PR DESCRIPTION
**Pull request by nh13**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/fastquorum/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/fastquorum _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by SPPearce** [comment]
Hi Nils,
What exactly is the high-throughput part here?

**Comment by SPPearce** [comment]
Ok, figured out the two branches by looking at your other PR.
I'm finding it hard to read the right hand side of the subway map, why does it have a black background?

**Comment by nh13** [comment]
> What exactly is the high-throughput part here?
See: https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md

> I'm finding it hard to read the right hand side of the subway map, why does it have a black background?
There are two phases to the pipeline, (1) to get to grouped reads from FASTQ, and (2) to get from grouped reads to consensus calls.  There are two versions of Phase 2 R&D and high-throughput, and so I wanted to differentiate between those two, one with a grey background and one with a black background.

**Comment by nh13** [comment]
Merging so we can at least have one image, can improve it later if needed

**Pull request merged**
