### PR TITLE
Enable validation lenient mode to allow filter_min_reads to be an integer or string

### LINKED ISSUE #62: Fix passing filter_min_reads as int
### Description of the bug

When analyzing non-duplex reads it makes sense to set filter_min_reads to an int, however. when setting `--filter_min_reads 1` you will encounter the following error:
` --filter_min_reads: expected type: String, found: Integer (1)`

even passing --filter_min_reads "1" does not seem to solve this issue.

### Command used and terminal output

```console
nextflow run nf-core/fastquorum --input $sample_sheet --outdir $outdir --fasta $reference_fasta --mode rd --groupreadsbyumi_strategy Identity --groupreadsbyumi_edits 0 --duplex_seq false --filter_min_reads 1 -profile docker -resume

Error message: 
--filter_min_reads: expected type: String, found: Integer (1)
```

### Relevant files

_No response_

### System information

Nextflow version: 24.04.2
Hardware: HPC
Executor: slurm
Container: docker/singularity
OS: Ubuntu
nf-core/fastquorum v1.0.1dev

### PR DESCRIPTION
**Pull request by SPPearce**
Fixes #62

### CODE REVIEW

**Review by nh13 — CHANGES_REQUESTED** [review]
I don't think we want to make the validation less strict (i.e. lenient), since that will apply to all arguments.  Looking at other nf-core pipeliens, they keep it strict.

Instead, I think we want those specific arguments to support either an integer or string, which is supported by the JSON schema used here: https://json-schema.org/understanding-json-schema/reference/type

**Comment by nh13** [comment]
@SPPearce I've implemented my suggestion here: https://github.com/nf-core/fastquorum/pull/66

**Comment by SPPearce** [comment]
Ok, that is fine, wasn't aware you could allow multiple types.

**Comment by nh13** [comment]
Me either!

**Pull request closed without merging**
